// Generated by TMBtools: do not edit by hand

#define TMB_LIB_INIT R_init_LocalCop_TMBExports
#include <TMB.hpp>
#include "dclayton.hpp"
#include "hclayton.hpp"
#include "pclayton.hpp"
#include "pfrank.hpp"

template<class Type>
Type objective_function<Type>::operator() () {
  DATA_STRING(model);
  if(model == "dclayton") {
    return dclayton(this);
  } else if(model == "hclayton") {
    return hclayton(this);
  } else if(model == "pclayton") {
    return pclayton(this);
  } else if(model == "pfrank") {
    return pfrank(this);
  } else {
    Rf_error("Unknown model.");
  }
  return 0;
}
